services:
  db-updated:
    image: mariadb
    container_name: chamilo_db_updated
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: chamilo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data_updated:/var/lib/mysql
      - ./dump-updated.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - chamilo_net_updated

  chamilo-updated:
    image: patrickhalasik/chamilo-csrf:1.11.12
    container_name: chamilo_app_updated
    ports:
      - "8083:80"
    volumes:
      - chamilo_data_updated:/var/www/html
    environment:
      - DATABASE_HOST='db-updated'
      - DATABASE_NAME='chamilo'
      - DATABASE_USER='root'
      - DATABASE_PASSWORD='root'
    depends_on:
      - db-updated
    networks:
      - chamilo_net_updated

  malicious-csrf-page-updated:
    image: patrickhalasik/chamilo-malicious-csrf-page:1.11.12
    container_name: chamilo_malicious_csrf_page_updated
    ports:
      - "8084:80"

volumes:
  db_data_updated:
  chamilo_data_updated:

networks:
  chamilo_net_updated:
